import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { Post } from '@prisma/client';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='container mx-auto min-h-screen p-4'>
				<Posts />
			</main>
		</>
	);
};

const Posts = () => {
	const { data: posts, isLoading } = trpc.useQuery(['post.getAll'], {
		onSuccess: (posts: Post[]) => console.log(posts),
	});

	if (isLoading) return <div>Loading...</div>;

	return (
		<>
			{posts?.map((p: Pick<Post, 'id' | 'title' | 'body'>, i: number) => {
				return <Post key={i} post={p} />;
			})}
		</>
	);
};

const Post = ({ post }: { post: Pick<Post, 'id' | 'title' | 'body'> }) => {
	return (
		<Link href={`/${post.id}`}>
			<div className='border rounded-md p-4'>
				<h1 className='text-xl text-white'>{post.title}</h1>
			</div>
		</Link>
	);
};

export default Home;
